# standard environment (sudo: required) is provisioned with 7.5g memory, but has 50 minute time limit for jobs
# container-based environment (sudo: false) is provisioned with only 4g memory, but haven't run into time limit for jobs yet
sudo: false
language: java
before_install:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
    # NewRatio is to leave as much memory as possible to old gen
  - echo "MAVEN_OPTS=\"-Xmx768m -XX:NewRatio=20\"" > ~/.mavenrc
install: true
script:
    # travis ci provides a default settings xml that has lots of unnecessary repositories which slows build down
  - rm ~/.m2/settings.xml
  - build/travis-ci/build.sh $TARGET
